spring:
  application:
    name: UX

eureka:
  client:
    serviceUrl:
          defaultZone: http://${eureka.hostname}:10090/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

      
