spring:
  application:
    name: UX


eureka:
  client:
    serviceUrl:
          defaultZone: http://${eureka.hostname}:10090/eureka/
  instance: 
    nonSecurePortEnabled: false
    hostname: localhost
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}

      
