server:
  port: 10092
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: ZUUL
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: ZUUL

ribbon:
  IsSecure: true
  eureka:
    enabled: true



  

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    test:
      path: /**
      serviceId: main
#     url: https://localhost:10091